### ISSUE TITLE
Number of OSS-Fuzz bugs vs Number of OSV-Fuzz Vulns

### ISSUE THREAD

**Issue by bennofs** [google/osv#162]
There are about 6000 OSS-Fuzz issues tagged as bug-security: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=Type%3DBug-Security%20-status%3AWontFix%2CDuplicate&can=1

However, the OSS Fuzz Vuln Data only contains about 1500 Vulnerabilities. Why is that the case? It seems that early issues, like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9&q=Type%3DBug-Security%20-status%3AWontFix%2CDuplicate&can=1, are not present?

**Comment by oliverchang** [comment]
Hi,

Yes, unfortunately we weren't able to backfill all of our data to the older ones, due to build system issues making bisection difficiult.
