### ISSUE TITLE
Fix package name and namespace for the log4shell

### ISSUE THREAD

**Issue by prabhu** [google/osv#277]
It appears like osv is reporting with an incorrect package url: `Maven/org.ops4j.pax.logging:pax-logging-log4j2`

https://osv.dev/vulnerability/GHSA-xxfh-x98p-j8fr

Consider using `org.apache.logging.log4j:log4j-core`

https://github.com/advisories/GHSA-jfh8-c2jp-5v3q

Bonus points: ignore `org.apache.logging.log4j:log4j-api` which is not vulnerable.

**Comment by oliverchang** [comment]
Hi @prabhu. Thanks for reporting. We simply take what's in GHSA and don't modify anything there. 

This corresponds to https://github.com/advisories/GHSA-xxfh-x98p-j8fr, which matches the OSV entry.

The main log4shell entry that references `org.apache.logging.log4j:log4j-core` is https://osv.dev/vulnerability/GHSA-jfh8-c2jp-5v3q.

Please comment if I've misunderstood anything here.

**Comment by prabhu** [comment]
@oliverchang Silly me. Was indeed looking at the wrong link! Could you consider my second request to remove log4j-api from your database?

The original GitHub filing is deliberately incorrect to really make dependabot work correctly. Perhaps you can consider this for triaging.

```
## Affected packages
Only the `org.apache.logging.log4j:log4j-core` package is directly affected by this vulnerability. The `org.apache.logging.log4j:log4j-api` package is included on this advisory to prevent version desync which may occur as a result of dependabot actions.
```
