### ISSUE TITLE
Fetch all data through API

### ISSUE THREAD

**Issue by maitrayshah** [google/osv#306]
Question - Is it possible to dump all vulnerabilities through OSV API ?
Something like https://api.osv.dev/v1/all

- I checked the [GCS zip](https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip) but it would be nice if I can just fetch all vulnerabilities as a JSON response rather than downloading zip and merging on my end. 
- Also the UI is using [URL](https://osv.dev/backend/query?page=1&search=&affected_only=true&ecosystem=Go), I wanted to check if its safe to use or could change anytime.

Thanks

**Comment by oliverchang** [comment]
The [GCS bucket](https://github.com/google/osv#current-data-sources) is the only recommended way to get all aggregated vulnerabilities from OSV.

If you don't want to unzip, you can also do a [bucket listing](https://cloud.google.com/storage/docs/listing-objects) to iterate through all individual JSON files there. Would that work for you? 

> Also the UI is using [URL](https://osv.dev/backend/query?page=1&search=&affected_only=true&ecosystem=Go), I wanted to check if its safe to use or could change anytime.

Unfortunately this is not stable and subject to change any time. It also has much stricter rate limiting.

**Comment by maitrayshah** [comment]
Thanks a lot for that information. I will stick to using GCS bucket option then and let me check out bucket listing to iterate through the files. 
Is there any rate limiting on the GCS bucket URL ?

**Comment by oliverchang** [comment]
> Thanks a lot for that information. I will stick to using GCS bucket option then and let me check out bucket listing to iterate through the files. Is there any rate limiting on the GCS bucket URL ?

Great! You shouldn't run into any rate limiting issues by listing objects in this bucket.
