### ISSUE TITLE
Clarify licensing of data

### ISSUE THREAD

**Issue by JamieMagee** [google/osv#319]
Is it possible to clarify the licensing of the distributed data? There appears to be a mix:

- [GitHub Security Advisories](https://github.com/github/advisory-database/blob/main/LICENSE.md) is CC-BY 4.0
- [PyPI Advisory Database](https://github.com/pypa/advisory-database/blob/main/LICENSE) is CC-BY 4.0
- [Go Vulnerability Database](https://github.com/golang/vulndb#license) is CC-BY 4.0
- [Rust Advisory Database](https://github.com/rustsec/advisory-db/blob/main/LICENSE.txt) is CC0 1.0
- [Global Security Database](https://github.com/cloudsecurityalliance/gsd-database/blob/main/LICENSE) is CC0 1.0
- [OSS-Fuzz](https://github.com/google/oss-fuzz-vulns/blob/main/LICENSE) is CC-BY 4.0

**Comment by oliverchang** [comment]
Thanks, that's a very good point. I'll clarify these!
