### ISSUE TITLE
Include osv-detector in list of command line tools

### ISSUE THREAD

**Issue by G-Rath** [google/osv#414]
I see a new v2 UI has been launched for osv.dev - it looks really nice!

I noticed there was a "Command line tools" section, and was wondering if you'd be open to listing [`osv-detector`](https://github.com/G-Rath/osv-detector) there as I think it would greatly help increase visibility of the project.

**Comment by oliverchang** [comment]
> I see a new v2 UI has been launched for osv.dev - it looks really nice!

Thanks!!

> I noticed there was a "Command line tools" section, and was wondering if you'd be open to listing [osv-detector](https://github.com/G-Rath/osv-detector) there as I think it would greatly help increase visibility of the project.

This is amazing :) But I think we'd like to review this a little before we fully endorse it on the home page. Perhaps we can have a list of third party tools somewhere and link your tool from there to start with?

Very interested to collaborate more on osv-detector though!!

**Comment by G-Rath** [comment]
No problem - having a home page endorsement would be super awesome but understand that also would imply an amount of trust in the endorsed project; any linkage to the project would be appreciated. 

Let me know if there's anything in particular you'd like to review or discuss about the project too.

**Comment by oliverchang** [comment]
I uploaded a PR to add a third party tools section (with this tool as the first :) )
