### ISSUE TITLE
Log import issue

### ISSUE THREAD

**Issue by Agostinelli** [google/osv#431]
Hi,

The current version of the scanner has an issue with the `log` library not being used. This prevents the tool from running.

The commit that introduced the bug is the latest commit: 168a6b2c593d4fac2defbc8546e634256cdfa5b0

Suggested fix: remove the log import, or put a `_` in front of it.

Impact: As of now, the tool cannot be run with `go run` and other compilation tools are not working. 

Thanks

**Comment by oliverchang** [comment]
Thanks @sbassett29 for the PR!
