### ISSUE TITLE
Differentiate "no vulnerabilities" from "couldn't match component"

### ISSUE THREAD

**Issue by JosiahOne** [google/osv#432]
(This may not be possible if the OSV DB only stores vulnerabilities and has no separate way to "locate" components)

Say you make a request to OSV asking for vulnerabilities in `accorn 7.0.0` in the `npm` environment. You'll get back `{}`. This is perfectly correct, but a bit unhelpful.

The intent of the requester was to lookup `acorn 7.0.0` (which does have vulnerabilities) but typo'd it. You could imagine similar errors where a name alias is used.

A helpful property of some SCA-style tools is that they can differentiate two cases:

1. The component could not be found
2. The component was found, but (as far as we can tell) there are no vulnerabilities.

Would be great if the OSV API could return similar kinds of metadata. This would allow clients to notify users when dependencies couldn't be found and might need review.

**Comment by oliverchang** [comment]
Thanks! This is a great idea, but I'm not sure if the OSV API is the right place to validate this.

To serve our queries efficiently, we index and query the packages we know about, which is going to be a small subset of all packages in existence. The best way to check for this validity is to check against the actual package managers (e.g. npm, PyPI) for existence. Adding this dependency to the API adds a fair bit of complexity. 

Would it make more sense to have tooling which makes the API calls validate this instead?

**Comment by JosiahOne** [comment]
No that's fair and totally doable! Thanks for the response!

**Comment by oliverchang** [comment]
Thanks! I'll close this then :)
