### ISSUE TITLE
Generic pipeline for importing Vulnerabilities.

### ISSUE THREAD

**Issue by oliverchang** [google/osv#44]
Extend the current OSS-Fuzz pipeline to support generic data sources.

- Input: Partially filled [Vulnerability](https://osv.dev/docs/#tag/vulnerability_schema) data from a repository.
- Output: Vulnerability with appended affected commit range and versions info pushed back to the same repository and location. 

More requirements:
- Parts of OSV will also be made to run as part of CI workflows (#51)
- Users can also submit PRs to fix up details in Vulnerability entries.
- OSS-Fuzz data will be dumped as well in the same format.

Current sketch (subject to change):

![Architecture](https://user-images.githubusercontent.com/759062/106834907-681c5600-66ea-11eb-85ce-eb359e32f84f.png)

**Comment by westurner** [comment]
This may be a duplicate? 
"Existing artifact vuln scanners, databases, and specs?" #55
