### ISSUE TITLE
API & databases seem to lost a lot of OSVs

### ISSUE THREAD

**Issue by G-Rath** [google/osv#451]
I'm hoping you're already aware, but it seems like osv.dev is having some data issues:

```
osv-detector-t --cache-all-databases
  Loading OSV databases for the following ecosystems:
    npm (0 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:53:22 GMT)
    crates.io (394 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:59:03 GMT)
    RubyGems (0 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:53:21 GMT)
    Packagist (1 vulnerability, including withdrawn - last updated Thu, 09 Jun 2022 01:59:04 GMT)
    Go (156 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:59:04 GMT)
    Maven (3 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:59:05 GMT)
    PyPI (2070 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:54:28 GMT)
```

```
❯ osv-detector-t --use-api .
Gemfile.lock: found 230 packages
  Loading OSV databases for the following ecosystems:
    RubyGems (0 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:53:21 GMT)

  no known vulnerabilities found

yarn.lock: found 1164 packages
  Loading OSV databases for the following ecosystems:
    npm (0 vulnerabilities, including withdrawn - last updated Thu, 09 Jun 2022 01:53:22 GMT)

  no known vulnerabilities found
```

While I'm demonstrating with `osv-detector`, the vulnerability library on osv.dev and api are affected too, though the counts on the site are unaffected (I'm assuming they're cached or precomputed, which is good for showing something is wrong):

![image](https://user-images.githubusercontent.com/3151613/172748329-ac008a80-092b-4543-97fa-b88fca25d276.png)

I was using it fine this morning.

**Comment by oliverchang** [comment]
Yep, this is an issue with the GitHub advisory repo. The automation cron seems to repeatedly delete entries at https://github.com/github/advisory-database/tree/main/advisories/github-reviewed/2022.

I've already raise this issue with them.

**Comment by oliverchang** [comment]
In the meantime I've forked the repo and reset it to its last known good state and pointed OSV to that. These should start coming back shortly.

**Comment by oliverchang** [comment]
The issues seem to be resolved. I've re linked OSV with the actual GitHub repo.
