### ISSUE TITLE
SSL Certificate not verifying

### ISSUE THREAD

**Issue by nikhilkhandelwal07** [google/osv#453]
Not able to verify the SSL certificate in the API

**Comment by oliverchang** [comment]
I'm not able to reproduce this. Could you please provide more details?

**Comment by nikhilkhandelwal07** [comment]
Hi
I was trying to use the osv API with the link https://api.osv.dev/v1/query.  I
am using the POST method to get vulnerability information for different
modules of npm and rust. However, when I send a request to the API using
axios or even postman it is throwing an SSL error and if I remove the
authentication it works. However, since it is not a good practice to verify
the authentication, I need you to help to figure this out.

**Comment by oliverchang** [comment]
I am unable to reproduce this. The cert on the API works for me. What may be happening is you have a local misconfiguration or some MITM proxy intercepting traffic here.

**Comment by nikhilkhandelwal07** [comment]
Hello Sir
PFA the screenshot of the error I am getting for your reference.
[image: image.png]
