### ISSUE TITLE
Make it work without any client-side JavaScript

### ISSUE THREAD

**Issue by KOLANICH** [google/osv#56]
>We're sorry but frontend2 doesn't work properly without JavaScript enabled. Please enable it to continue.

You are not sorry, if you were sorry, this website wouldn't have tried to coerce me into enabling JS.

Also https://osv.dev/docs/ don't work.

**Comment by oliverchang** [comment]
Hi,

Unfortunately we don't have the resources to devote to maintaining a JS-free frontend. 

We will have an option for you to consume the data without having JS enabled, as our data will be exported to a repository as plain YAML files (see https://github.com/google/osv/issues/44).

**Comment by KOLANICH** [comment]
> Unfortunately we don't have the resources to devote to maintaining a JS-free frontend.
> we = Google
> Google doesn't have resources.

I don't beleive.

>We will have an option for you to consume the data without having JS enabled, as our data will be exported to a repository as plain YAML files (see #44).

Thanks, how about also making the site with docs no-JS?
