### ISSUE TITLE
Support for packageurl

### ISSUE THREAD

**Issue by sameer1046** [google/osv#64]
Support to identify package with package url would be nice and it will be easy to integrate with other tool chain.
https://github.com/package-url/purl-spec

**Comment by pombredanne** [comment]
I could not agree more!

**Comment by oliverchang** [comment]
Hi!

Could I ask where you are suggesting to add support for purls? As part of an API query? 

Our thinking with our current schema and API is to keep it compatible with PURLs where we can, i.e. keeping the "ecosystem" values consistent with the ones chosen by purl ("golang", "pypi" etc), so that in most cases you can just split the PURL into the ecosystem name and the package path and version and still have it accepted by OSV.

**Comment by sameer1046** [comment]
That is correct. But if purl will be supported in api query then it will be easily integrated with other open source tools like owasp dependency track.

**Comment by oliverchang** [comment]
We support PURL API requests now:

```
curl -X POST -d '{"package": {"purl": "pkg:maven/org.apache.struts:struts2-core"}, "version": "2.0.14"}' https://api.osv.dev/v1/query
```

But @VinodAnandan pointed out that we don't support package URLs with versions in them. e.g. "pkg:maven/org.apache.struts:struts2-core@2.0.14". Re-opening to consider this feature.

**Comment by nscuro** [comment]
First, thank you for implementing PURL support! 🚀

In addition to the missing version though, the PURL syntax isn't quite right yet either.

PURL is defined as:
```
scheme:type/namespace/name@version?qualifiers#subpath
```

For the `maven` type, `groupId` maps to `namespace` and `artifactId` to `name`, see [here](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#maven). So the correct PURL for the example above would be:
```
pkg:maven/org.apache.struts/struts2-core
```

Currently, the following does not yield any results:
```shell
$ curl -X POST -d '{"package": {"purl": "pkg:maven/org.apache.struts/struts2-core"}, "version": "2.0.14"}' https://api.osv.dev/v1/query
```

**Comment by oliverchang** [comment]
Thanks for pointing that out @nscuro. I have a PR out and this should be fixed shortly. 

Querying by PURLs that have versions in them will also come shortly.

**Comment by oliverchang** [comment]
`curl -X POST -d '{"package": {"purl": "pkg:maven/org.apache.struts/struts2-core@2.0.14"}}' https://api.osv.dev/v1/query` now works!

**Comment by VinodAnandan** [comment]
Thank you @oliverchang !!
